kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: widgety-pf-pipeline
  namespace: demo-dev
  labels:
    app: widgety-pf
    build: widgety-pf
    name: widgety-pf-dev-pipeline
    type: image
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'widgety-pf:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/jkube/jkube-java:0.0.24'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  runPolicy: Serial
