apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: widgety-pf-qa-build-pipeline
  namespace: tekton-pipelines
  labels:
    app: widgety-pf
spec:
  params:
    - name: git-repository-url
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-repository-url)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: workspace
    - name: maven-verify
      taskRef:
        name: maven
        kind: ClusterTask
      params:
        - name: MAVEN_IMAGE
          value: 'registry.access.redhat.com/ubi8/openjdk-17:1.21-1'
        - name: GOALS
          value:
            - '-B'
            - '-ntp'
            - verify
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
      runAfter:
        - git-clone
    - name: maven-extract-project-version
      taskRef:
        name: maven-extract-project-version
        kind: Task
      workspaces:
        - name: source
          workspace: workspace
      runAfter:
        - git-clone
    - name: buildah-build-and-push
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: DOCKERFILE
          value: 'Dockerfile'
        - name: IMAGE
          value: 'quay.io/cziesman/widgety-pf-qa:$(tasks.maven-extract-project-version.results.version)'
      workspaces:
        - name: source
          workspace: workspace
      runAfter:
        - maven-extract-project-version
        - maven-verify
    - name: deploy-task
      taskRef:
        name: deploy-to-openshift
      params:
        - name: image-url
          value: 'quay.io/cziesman/widgety-pf-qa:$(tasks.maven-extract-project-version.results.version)'
        - name: deployment-name
          value: widgety-pf
        - name: namespace
          value: widgety-pf-qa
      runAfter:
        - buildah-build-and-push
  finally:
    - name: send-status-to-slack
      params:
        - name: token-secret
          value: slack-token
        - name: channel
          value: all-cetars-demo
        - name: message
          value: "Pipeline <widgety-pf-qa-build> completed with status <$(tasks.status)>."
      taskRef:
        name: send-to-channel-slack
  workspaces:
    - name: workspace
    - name: maven-settings