apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-with-branch
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-commit-message
      value: $(body.head_commit.message)
    - name: git-repository-url
      value: $(body.repository.url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: content-type
      value: $(header.Content-Type)
    - name: pusher-name
      value: $(body.pusher.name)
    - name: git-branch
      value: $(body.ref)