#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: tekton-pvc
#  namespace: widgety-pf-dev
#spec:
#  accessModes:
#    - ReadWriteOnce
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 1Gi