apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: widgety-pf-prod-trigger-template
  namespace: tekton-pipelines
  labels:
    app: widgety-pf
spec:
  params:
    - name: git-repository-url
      description: The repository URL from the GitHub webhook
      default: "https://github.com/cziesman/widgety-pf.git"
    - name: git-branch
      description: The branch ref from the GitHub webhook
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: widgety-pf-prod-pipeline-
      spec:
        pipelineRef:
          name: widgety-pf-prod-pipeline
        params:
          - name: git-repository-url
            value: $(tt.params.git-repository-url)
          - name: git-branch
            value: $(tt.params.git-branch)
        workspaces:
          - name: maven-settings
            emptyDir: {}
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi