apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: widgety-pf-prod-event-listener
  namespace: tekton-pipelines
  labels:
    app: widgety-pf
spec:
  serviceAccountName: pipeline
  triggers:
    - name: widgety-pf-prod-trigger
      bindings:
        - ref: github-push-with-branch
          kind: TriggerBinding
        - ref: github-tag
          kind: TriggerBinding
      interceptors:
        - params:
            - name: 'filter'
              value: "body.ref.contains('refs/tags')"
            - name: 'overlays'
              value: |
                [
                  {
                    "key": "extensions.tagSubstring",
                    "expression": "body.ref.replaceAll('refs/tags/(.*)', '\\1')"
                  }
                ]
          ref:
            name: 'cel'
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: widgety-pf-github-webhook-secret
                secretKey: token
            - name: "eventTypes"
              value: [ "push" ]
      template:
        ref: widgety-pf-prod-trigger-template