
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: widgety-pf
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
    log-request-details: true

springdoc:
  api-docs:
    path: /api-docs

#logging:
#  level:
#    root: INFO
#    com.redhat: TRACE
#    org.springframework: INFO
#  pattern:
#    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M:%line - %msg%n"

joinfaces:
#  primefaces:
#    theme: saga
#    theme: vela
#    theme: arya
  jsf:
    webapp-resources-directory: /resources
