kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: widgety-pf
  namespace: widgety-pf-dev
  labels:
    app: widgety-pf
    build: widgety-pf
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: {}
      from:
        kind: DockerImage
        name: 'quay.io/cziesman/widgety-pf:2.0.0-SNAPSHOT'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
status:
  dockerImageRepository: 'image-registry.openshift-image-registry.svc:5000/widgety-pf-dev/widgety-pf'
