kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: widgety-pf
  namespace: widgety-pf-dev
  labels:
    app: widgety-pf
    build: widgety-pf
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 2.0.0-snapshot
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/cziesman/widgety-pf-dev:2.0.0-snapshot'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
