kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-deploy
  namespace: widgety-pf-dev
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"pipeline-deploy","namespace":"widgety-pf-dev"},"rules":[{"apiGroups":["apps",""],"resources":["deployments","namespaces"],"verbs":["patch"]}]}
rules:
  - verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
      - patch
    apiGroups:
      - apps
      - ''
    resources:
      - deployments
      - pods
      - services
      - namespaces
  - verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
