kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-deploy
  namespace: widgety-pf-dev
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-deploy
