apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: widgety-pf-dev-build-event-listener
  namespace: widgety-pipelines
  labels:
    app: widgety-pf
spec:
  serviceAccountName: pipeline
  triggers:
    - name: widgety-pf-dev-build-trigger
      bindings:
        - ref: github-push
          kind: ClusterTriggerBinding
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: widgety-pf-github-webhook-secret
                secretKey: token
            - name: "eventTypes"
              value: [ "push" ]
      template:
        ref: widgety-pf-build-trigger-template