apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: widgety-pf-dev-build-event-listener
  namespace: widgety-pipelines
  labels:
    app: widgety-pf
spec:
  serviceAccountName: pipeline
  triggers:
    - name: widgety-pf-dev-build-trigger
      bindings:
        - ref: github-push-with-branch
          kind: ClusterTriggerBinding
      interceptors:
        - params:
            - name: filter
              value: "body.ref == 'refs/heads/dev'"
            - name: overlays
              value:
                - key: "extensions.triggers.tekton.dev/precondition-failed"
                  expression: "body.ref != 'refs/heads/dev'"
          ref:
            name: cel
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: widgety-pf-github-webhook-secret
                secretKey: token
            - name: "eventTypes"
              value: [ "push" ]
      template:
        ref: widgety-pf-build-trigger-template